steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia.gcr.io/soulmint/soulquest', '-f' , 'Dockerfile' , '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia.gcr.io/geniam2a/workspace' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'soulquest'
      - '--image'
      - 'asia.gcr.io/soulmint/soulquest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - asia.gcr.io/soulmint/soulquest
